# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de6a97e41ad5f198c3c66cad44b7a742560f21432f9b8d4dba476acbb6c2126b43215e84cf58eefca30c4695c26cbe77d56bd47358ae2a3b4c692e6da301687d

test:
  secret_key_base: 9552c6102a9d9e3a0497578633097d71c366e684569c7f9f94dbd55b3d71bd020be1d3d600bd5f229cf5130c60dc10cf9aaed2385db3d217adba9df257bf07a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
